import fcru
import fdensenet
import fdpn
import finception_resnet_v2
import flightcnn
import fmnasnet
import fmobilenet 
import fmobilenetv2
import fmobilefacenet
import fnasnet
import fpeleefacenet
import fresnet
import fresnest
import fsmall
import fspherenet
import fxception
